# Generated by Django 3.2 on 2021-06-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default='Fashion is part of the daily air and it changes all the time.', max_length=1000),
        ),
    ]
