# Generated by Django 3.2.2 on 2021-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
