# Generated by Django 3.2.2 on 2021-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210528_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
